/**
 * [INPUT]: Depends on knowledge-db schema and starter cross-checked guidance
 * [OUTPUT]: Provides high-frequency combination guidance entries
 * [POS]: Starter detail layer that prevents generic AI analysis without becoming a rule engine
 * [PROTOCOL]: Update this header when changed, then check AGENTS.md/CLAUDE.md
 */

import type { KnowledgeEntry } from '../schema'

const SOURCE_REFS = [
  'project.analysis-position',
  'book.lu-wang-star-nature',
  'book.wang-tingzhi-basic',
  'book.wang-tingzhi-stars',
  'book.ziwei-doushu-jingcheng',
  'author.cross-check',
]

export const COMBO_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'combo.ziwei.life-palace.guidance',
    domain: 'combo',
    title: '紫微在命宫',
    entities: ['紫微', '命宫'],
    appliesTo: ['命宫'],
    topics: ['性情', '格局', '责任', '自尊'],
    priority: 82,
    guidance: {
      focus: ['自尊与体面感', '统筹和承担责任的能力', '是否有辅弼昌曲等吉曜帮助', '是否被煞忌转为孤高或压力'],
      likelyThemes: ['重视秩序和身份感', '愿意承担核心责任', '对自己和环境要求较高'],
      nuance: ['紫微不等于必然富贵，需看辅曜、煞曜、三方四正和四化', '缺少助力时，统御欲可能变成孤立感或不易低头'],
      avoid: ['不要直接断大富大贵', '不要只写领导力而忽略自尊负担和环境配合'],
    },
    taskFit: {
      natal: '用于命格总断和性情分析。',
      match: '用于解释关系中对体面、尊重和主导权的需求。',
      share: '适合提炼成自尊、责任和不轻易低头的金句。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.76,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.wuqu.hua-ji.wealth.guidance',
    domain: 'combo',
    title: '武曲化忌与财务课题',
    entities: ['武曲', '化忌', '财帛宫'],
    appliesTo: ['财帛宫', '财运'],
    topics: ['财务压力', '现金流', '风险控制'],
    priority: 92,
    guidance: {
      focus: ['收入是否依赖专业和执行力', '现金流和账目压力', '投资判断是否过硬', '是否有吉曜缓和或煞曜加重'],
      likelyThemes: ['财务责任较重', '赚钱不宜靠侥幸', '容易因钱、账、合约或资金安排反复费心'],
      nuance: ['武曲化忌不等于必然破财，可表现为辛苦得财、守财压力或财务责任', '若运限引动且煞曜重，才提高明显破耗风险'],
      avoid: ['不要断言必破财', '不要建议高风险投资', '不要脱离财帛宫主题泛讲性格'],
    },
    taskFit: {
      natal: '用于财运和金钱观分析。',
      yearly: '若流年或大限引动，可提示现金流、合同和预算管理。',
      kline: '用于财务维度下行压力和波动加权。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.76,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.pojun.spouse-palace.guidance',
    domain: 'combo',
    title: '破军在夫妻宫',
    entities: ['破军', '夫妻宫'],
    appliesTo: ['夫妻宫', '感情'],
    topics: ['关系变化', '自由', '磨合'],
    priority: 84,
    guidance: {
      focus: ['关系里的自由度和变化需求', '相处是否经历阶段性重建', '伴侣或关系模式是否带开创、破旧立新的气质'],
      likelyThemes: ['亲密关系不喜欢过度静态', '感情容易因现实阶段改变而重新调整', '需要尊重彼此边界'],
      nuance: ['破军不应直接断离散，可理解为关系需要不断更新和重建秩序', '吉曜可转为共同开创，煞忌重时才加大冲突与消耗'],
      avoid: ['不要直接断离婚', '不要把所有变化都写成负面', '不要忽略双方成熟度和沟通方式'],
    },
    taskFit: {
      natal: '用于婚恋模式分析。',
      match: '用于说明关系磨合点和边界需求。',
      yearly: '若流年引动夫妻宫，可提示关系阶段变化。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.74,
    reviewStatus: 'draft',
  },
  {
    id: 'pattern.sha-po-lang.guidance',
    domain: 'pattern',
    title: '杀破狼格局导向',
    entities: ['七杀', '破军', '贪狼', '杀破狼'],
    appliesTo: ['命宫', '三方四正', '格局'],
    topics: ['开创', '变化', '波动', '突破'],
    priority: 86,
    guidance: {
      focus: ['人生阶段是否多变动', '是否适合开创型环境', '风险承受和自我约束能力', '吉煞四化如何决定成败质量'],
      likelyThemes: ['不安于稳定重复', '适合在变化中寻找机会', '人生起伏比静态格局更明显'],
      nuance: ['杀破狼不是单纯凶格，重点在开创、破局和代价', '若缺少纪律和资源承接，变化可能转为消耗'],
      avoid: ['不要只写动荡凶险', '不要忽略其开创和突破能力', '不要脱离三方四正确认格局强弱'],
    },
    taskFit: {
      natal: '用于命格总断和职业倾向。',
      yearly: '运限引动时可提示转型、迁动、项目变化。',
      kline: '适合提高人生曲线波动幅度。',
      share: '适合提炼成破局、重建、敢变的表达。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.74,
    reviewStatus: 'draft',
  },
  {
    id: 'pattern.ji-yue-tong-liang.guidance',
    domain: 'pattern',
    title: '机月同梁格局导向',
    entities: ['天机', '太阴', '天同', '天梁', '机月同梁'],
    appliesTo: ['命宫', '三方四正', '官禄宫'],
    topics: ['文职', '服务', '策划', '稳定'],
    priority: 82,
    guidance: {
      focus: ['思考、服务、文教、策划和制度内发展', '是否有稳定环境承接其细腻和协调能力'],
      likelyThemes: ['适合靠专业、服务、规划、协调立身', '重视稳定和细节', '不一定适合粗暴冒进路线'],
      nuance: ['机月同梁应看星曜是否成组、宫位是否得力、是否被煞忌破坏', '若煞忌重，细腻可能转为多虑或压力'],
      avoid: ['不要机械断公职', '不要忽略实际宫位和现代职业转译'],
    },
    taskFit: {
      natal: '用于事业方向和性情分析。',
      yearly: '运限引动时可提示学习、文书、职务调整、服务型机会。',
      share: '适合提炼成聪明细腻、以专业服务成事的表达。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.72,
    reviewStatus: 'draft',
  },
  {
    id: 'pattern.zi-fu-tong-gong.guidance',
    domain: 'pattern',
    title: '紫府同宫格局导向',
    entities: ['紫微', '天府', '紫府同宫'],
    appliesTo: ['命宫', '三方四正', '格局'],
    topics: ['统筹', '资源', '守成', '格局'],
    priority: 88,
    guidance: {
      focus: ['紫微的主导力是否能被天府的资源承接', '格局是否重稳定、管理和长期经营', '是否有辅曜帮助其从守成转为开创'],
      likelyThemes: ['重秩序和安全感', '适合管理资源、组织团队和长期布局', '格局稳定但可能偏保守'],
      nuance: ['紫府同宫不等于自动富贵，需看宫位、辅煞、四化和三方四正', '若缺少行动星或受忌煞牵制，可能守得住但开拓不足'],
      avoid: ['不要直接断富贵双全', '不要忽略保守、慢热和资源承接条件'],
    },
    taskFit: {
      natal: '用于命格总断和事业资源分析。',
      yearly: '运限引动时看管理、资源配置和稳定经营。',
      kline: '可作为整体稳定性和抗波动因素。',
      share: '适合提炼成稳、能扛局面、有资源感的表达。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.74,
    reviewStatus: 'draft',
  },
  {
    id: 'pattern.zi-sha-tong-gong.guidance',
    domain: 'pattern',
    title: '紫杀同宫格局导向',
    entities: ['紫微', '七杀', '紫杀同宫'],
    appliesTo: ['命宫', '官禄宫', '格局'],
    topics: ['权威', '开创', '压力', '决断'],
    priority: 86,
    guidance: {
      focus: ['紫微的统筹是否能驾驭七杀的冲劲', '是否适合高压、开创或竞争环境', '权威感和孤勇之间的平衡'],
      likelyThemes: ['有承担大局和破局的欲望', '适合在压力中取得位置', '容易对自己和他人要求高'],
      nuance: ['紫杀同宫要看是否有辅曜调和和煞忌加重', '格局强时是开创与统御，失衡时可能刚硬孤立'],
      avoid: ['不要只写霸气或凶险', '不要忽略纪律、团队和资源配合'],
    },
    taskFit: {
      natal: '用于命格开创性和事业压力分析。',
      yearly: '运限引动时看职权、竞争和转型。',
      kline: '可提高事业波动和突破倾向。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.72,
    reviewStatus: 'draft',
  },
  {
    id: 'pattern.sun-moon-reversed.guidance',
    domain: 'pattern',
    title: '日月反背格局导向',
    entities: ['太阳', '太阴', '日月反背'],
    appliesTo: ['命宫', '迁移宫', '格局'],
    topics: ['内外不一致', '名声', '安全感', '时机'],
    priority: 82,
    guidance: {
      focus: ['太阳与太阴的亮度和落点', '外在表现与内在安全感是否错位', '成事是否需要离乡、转场或等待时机'],
      likelyThemes: ['内外需求不容易同步', '早年或特定阶段较易感到不被看见', '需要找到适合自己发光和安顿的环境'],
      nuance: ['日月反背不宜直接断贫贱，应看现代环境、三方四正和运限是否补足', '可转译为自我表达与安全感之间的协调课题'],
      avoid: ['不要使用宿命化低格局断语', '不要脱离亮度和运限判断'],
    },
    taskFit: {
      natal: '用于性情、内外差异和发展时机分析。',
      yearly: '引动时看曝光、家庭、安全感和环境转场。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.68,
    reviewStatus: 'draft',
  },
  {
    id: 'pattern.chang-qu-support.guidance',
    domain: 'pattern',
    title: '昌曲文曜导向',
    entities: ['文昌', '文曲', '昌曲'],
    appliesTo: ['命宫', '官禄宫', '父母宫', '格局'],
    topics: ['文书', '表达', '审美', '学习'],
    priority: 80,
    guidance: {
      focus: ['学习、表达、文书和审美能力', '是否能通过证照、内容、写作、设计或专业表达加分', '是否被化忌引成文书差错'],
      likelyThemes: ['适合靠表达、知识、审美或文案能力增益', '在文书、考试、传播和专业包装上有发挥空间'],
      nuance: ['昌曲不是单纯读书好，也代表表达和形式修饰', '若逢化忌或煞重，要注意文书、合约、传播误差'],
      avoid: ['不要机械断学历高', '不要忽略现代职业里的内容和表达能力'],
    },
    taskFit: {
      natal: '用于学习、表达和专业包装分析。',
      yearly: '引动时看考试、合同、文书、内容发布。',
      share: '可增强金句的文采与表达感。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.7,
    reviewStatus: 'draft',
  },
  {
    id: 'pattern.yang-tuo-pressure.guidance',
    domain: 'pattern',
    title: '羊陀压力结构导向',
    entities: ['擎羊', '陀罗', '羊陀'],
    appliesTo: ['命宫', '三方四正', '格局'],
    topics: ['阻力', '冲突', '拖延', '磨炼'],
    priority: 80,
    guidance: {
      focus: ['阻力是突发冲撞还是长期拖磨', '压力是否来自人际、身体、财务或执行过程', '是否能把磨炼转成技术和耐力'],
      likelyThemes: ['事情不一定顺滑，常要靠硬功夫处理阻力', '擎羊偏直接冲撞，陀罗偏拖延缠绕'],
      nuance: ['羊陀不是绝对凶，应看是否落在关键宫位、是否与吉曜或四化同会', '现代输出适合写成阻力类型和风险管理'],
      avoid: ['不要直接断血光灾祸', '不要制造恐惧', '不要忽略磨炼带来的专业性'],
    },
    taskFit: {
      natal: '用于阻力类型和性格磨炼分析。',
      yearly: '引动时提示冲突、拖延、伤损风险和流程管理。',
      kline: '可提高低点波动和压力提示。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.68,
    reviewStatus: 'draft',
  },
  {
    id: 'concept.empty-palace.borrow-opposite.guidance',
    domain: 'concept',
    title: '空宫借对宫导向',
    entities: ['空宫', '对宫', '借星'],
    appliesTo: ['十二宫'],
    topics: ['宫位判断', '三方四正'],
    priority: 80,
    guidance: {
      focus: ['空宫不等于该领域空白', '需要借对宫星曜并结合三方四正', '观察大限流年引动时该宫如何显现'],
      likelyThemes: ['该宫主题受外部关系或对宫力量影响较明显', '表现可能比有主星宫位更依赖环境触发'],
      nuance: ['空宫判断要避免简单化，应看对宫、三方、辅煞和四化', '现代表达可转成“该领域更受互动和环境牵动”'],
      avoid: ['不要说空宫就是没有', '不要只看对宫而忽略三方四正'],
    },
    taskFit: {
      natal: '用于解释无主星宫位。',
      yearly: '流年引动空宫时，用对宫和三方补足分析。',
      match: '合盘中遇到夫妻宫空宫时避免误判关系为空。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.74,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.taiyin.hua-ji.relationship.guidance',
    domain: 'combo',
    title: '太阴化忌与情感安全感',
    entities: ['太阴', '化忌', '夫妻宫'],
    appliesTo: ['夫妻宫', '感情', '田宅宫'],
    topics: ['安全感', '情绪', '亲密关系', '家宅'],
    priority: 90,
    guidance: {
      focus: ['情绪安全感是否不足', '亲密关系中的猜测、委屈或冷处理', '家庭、居住、财宅议题是否牵动感情'],
      likelyThemes: ['容易在亲密关系里敏感多想', '需要稳定、照顾和可预期的相处方式', '家宅或金钱安全感可能影响关系质量'],
      nuance: ['太阴化忌不等于感情必坏，更常表现为安全感课题和情绪消化问题', '若有化科、吉曜或稳定宫位承接，可转为细腻照顾和谨慎经营'],
      avoid: ['不要直接断感情失败', '不要把敏感写成单纯负面', '不要忽略现实居住和财务安全感'],
    },
    taskFit: {
      natal: '用于情感、安全感和家宅分析。',
      yearly: '引动时提示关系情绪、居住和财宅压力。',
      match: '用于合盘中分析一方的情绪需求和安全感触发点。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.74,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.taiyang.hua-ji.public-role.guidance',
    domain: 'combo',
    title: '太阳化忌与名声责任',
    entities: ['太阳', '化忌', '官禄宫'],
    appliesTo: ['官禄宫', '父母宫', '事业'],
    topics: ['名声', '责任', '男性长辈', '公开事务'],
    priority: 86,
    guidance: {
      focus: ['公开表现是否吃力', '责任和付出是否不被看见', '父亲、上级、男性贵人或权威关系是否带压力'],
      likelyThemes: ['容易为名声、职责或他人期待耗力', '事业上需处理可见度和评价压力', '付出与回报不一定成正比'],
      nuance: ['太阳化忌不等于事业失败，也可能是承担过多、曝光压力或被误解', '若宫位得力，可转为以责任感磨出声望'],
      avoid: ['不要直接断父亲或事业有灾', '不要把所有压力都归咎于外界不公'],
    },
    taskFit: {
      natal: '用于事业、名誉和父系主题分析。',
      yearly: '引动时提示公开事务、职场评价和上级关系。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.72,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.jumen.hua-ji.communication.guidance',
    domain: 'combo',
    title: '巨门化忌与沟通是非',
    entities: ['巨门', '化忌', '迁移宫'],
    appliesTo: ['命宫', '迁移宫', '官禄宫', '交友宫'],
    topics: ['沟通', '口舌', '误解', '信息不透明'],
    priority: 88,
    guidance: {
      focus: ['言语表达是否引发误解', '合同、文书、沟通链路是否清楚', '是否容易因质疑、争辩或信息不透明而耗力'],
      likelyThemes: ['有洞察和追问能力，但也容易陷入口舌', '适合把怀疑转成研究、审查和专业表达'],
      nuance: ['巨门化忌不是不能说话，而是需要更重视证据、措辞和沟通场合', '若用于专业研究、法律、咨询，反而可成为深入能力'],
      avoid: ['不要只写小人是非', '不要鼓励沉默逃避', '不要忽略文书和证据管理'],
    },
    taskFit: {
      natal: '用于表达和人际风险分析。',
      yearly: '引动时提示沟通、合同、投诉、争议和信息确认。',
      match: '用于关系中误解和沟通方式分析。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.76,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.lianzhen.hua-ji.boundary.guidance',
    domain: 'combo',
    title: '廉贞化忌与边界纠葛',
    entities: ['廉贞', '化忌', '夫妻宫'],
    appliesTo: ['夫妻宫', '官禄宫', '命宫'],
    topics: ['边界', '名誉', '感情', '规则'],
    priority: 86,
    guidance: {
      focus: ['感情和人际边界是否清晰', '名誉、规则或制度压力', '欲望、责任和关系承诺之间是否拉扯'],
      likelyThemes: ['容易遇到复杂人事或情感议题', '需要以规则、边界和透明沟通化解纠葛'],
      nuance: ['廉贞化忌不宜直接断桃花祸事，重点在边界、名誉和责任处理', '若落官禄，也可能表现为制度审查、职场规则或公关压力'],
      avoid: ['不要直接断外遇或丑闻', '不要用道德审判式语言', '不要忽略制度和边界建设'],
    },
    taskFit: {
      natal: '用于感情、事业边界和名誉风险。',
      yearly: '引动时提示规则、合约、关系边界和声誉管理。',
      match: '用于关系中的吸引、边界和承诺分析。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.72,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.tianji.hua-ji.decision.guidance',
    domain: 'combo',
    title: '天机化忌与决策反复',
    entities: ['天机', '化忌', '命宫'],
    appliesTo: ['命宫', '官禄宫', '迁移宫'],
    topics: ['决策', '焦虑', '变动', '规划'],
    priority: 86,
    guidance: {
      focus: ['是否因信息过多而决策反复', '计划变动和执行落差', '脑力消耗、焦虑和睡眠作息压力'],
      likelyThemes: ['聪明但容易想太多', '擅长预案却可能迟迟不定', '适合建立清晰决策流程和截止点'],
      nuance: ['天机化忌不是笨拙，而是思虑和变化过度消耗', '若用于研究、技术、策划，可转成审慎和问题预判能力'],
      avoid: ['不要写成没有能力', '不要鼓励频繁推翻计划', '不要忽略作息和焦虑管理'],
    },
    taskFit: {
      natal: '用于思维方式和职业策略。',
      yearly: '引动时提示变动、规划、学习和决策压力。',
      kline: '可提高事业或精神压力维度波动。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.74,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.tanlang.hua-ji.desire.guidance',
    domain: 'combo',
    title: '贪狼化忌与欲望边界',
    entities: ['贪狼', '化忌', '福德宫'],
    appliesTo: ['命宫', '福德宫', '夫妻宫', '财帛宫'],
    topics: ['欲望', '社交', '消费', '边界'],
    priority: 84,
    guidance: {
      focus: ['欲望、兴趣和社交是否过度牵动', '消费、享乐、情感诱因和自我约束', '能否把才艺和人缘转成正向生产力'],
      likelyThemes: ['有吸引力和兴趣驱动，但容易被诱惑或短期满足牵动', '需要建立财务、情感和作息边界'],
      nuance: ['贪狼化忌不等于放纵败坏，也可能是欲望管理和才艺沉淀的课题', '若有专业承接，可把兴趣转为商业或创作能力'],
      avoid: ['不要用道德化语言评判欲望', '不要直接断桃花破财', '不要忽略才艺和商业转化可能'],
    },
    taskFit: {
      natal: '用于欲望结构、社交和消费习惯。',
      match: '用于关系吸引力和边界分析。',
      yearly: '引动时提示消费、社交、感情诱因和自律。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.72,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.tianji.career.guidance',
    domain: 'combo',
    title: '天机在官禄宫',
    entities: ['天机', '官禄宫'],
    appliesTo: ['官禄宫', '事业'],
    topics: ['事业', '策划', '技术', '变动'],
    priority: 88,
    guidance: {
      focus: ['职业是否依赖脑力、策划、技术、咨询或协调', '工作环境是否多变且需要快速应变', '决策反复和计划变更是否影响执行'],
      likelyThemes: ['适合企划、技术、研究、顾问、产品、运营和协调型工作', '事业路径可能多调整，靠学习和信息处理累积优势'],
      nuance: ['天机在官禄不宜机械断频繁换工作，重点是职业需要动脑和应变', '若化忌或煞重，需防过度规划、犹豫和执行落差'],
      avoid: ['不要把变动写成不稳定失败', '不要忽略技术、咨询和系统规划能力'],
    },
    taskFit: {
      natal: '用于事业方向和工作方式分析。',
      yearly: '运限引动时提示项目变动、学习、决策和沟通压力。',
      kline: '用于事业维度波动和转型倾向。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.74,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.wuqu.wealth-palace.guidance',
    domain: 'combo',
    title: '武曲在财帛宫',
    entities: ['武曲', '财帛宫'],
    appliesTo: ['财帛宫', '财运'],
    topics: ['财务', '执行', '理财', '现金流'],
    priority: 88,
    guidance: {
      focus: ['赚钱是否依靠专业、纪律和执行力', '理财是否重规则、成本和效率', '是否容易因财务责任显得紧绷'],
      likelyThemes: ['适合稳定积累、预算管理、金融财会、技术执行或经营管理', '对钱较认真，愿意为结果承担压力'],
      nuance: ['武曲财帛不等于轻松发财，更像靠硬功夫和管理能力得财', '若化忌或煞重，现金流、合约和投资判断更需谨慎'],
      avoid: ['不要直接断富', '不要给具体投资建议', '不要忽略财务压力和沟通成本'],
    },
    taskFit: {
      natal: '用于财运结构和金钱观。',
      yearly: '引动时提示现金流、预算、账目、合约和投资审慎。',
      kline: '用于财富维度评分。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.76,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.tanlang.spouse-palace.guidance',
    domain: 'combo',
    title: '贪狼在夫妻宫',
    entities: ['贪狼', '夫妻宫'],
    appliesTo: ['夫妻宫', '感情'],
    topics: ['吸引力', '桃花', '欲望', '边界'],
    priority: 88,
    guidance: {
      focus: ['关系中的吸引力、浪漫感和新鲜感需求', '双方是否重视社交、享受和情绪互动', '欲望、边界和承诺之间是否需要平衡'],
      likelyThemes: ['感情不宜过于沉闷，容易被魅力、才艺、社交氛围吸引', '相处中需要保留趣味和互动空间'],
      nuance: ['贪狼夫妻不应直接断烂桃花，关键在欲望管理和关系边界', '吉曜可转为浪漫和经营能力，煞忌重时才更需防暧昧纠葛'],
      avoid: ['不要直接断外遇或桃花祸', '不要用道德化语言', '不要忽略经营关系的新鲜感需求'],
    },
    taskFit: {
      natal: '用于感情模式和伴侣画像。',
      match: '用于合盘中的吸引力、边界和相处节奏。',
      yearly: '引动时提示社交、暧昧、消费和关系边界。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.74,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.jumen.life-migration.guidance',
    domain: 'combo',
    title: '巨门在命宫或迁移宫',
    entities: ['巨门', '命宫', '迁移宫'],
    appliesTo: ['命宫', '迁移宫'],
    topics: ['表达', '质疑', '沟通', '外部评价'],
    priority: 84,
    guidance: {
      focus: ['语言表达和质疑能力如何影响人际', '在外是否容易因说法、立场或信息差被误解', '是否适合把追问能力转成专业表达'],
      likelyThemes: ['善分析、会追问、能看见问题背面', '外部互动中要重视措辞、证据和信息透明'],
      nuance: ['巨门不是单纯口舌星，也代表研究、辨析和揭示隐藏问题', '落迁移时尤其要注意外部场合的表达策略'],
      avoid: ['不要只写招是非', '不要鼓励沉默回避', '不要忽略专业表达价值'],
    },
    taskFit: {
      natal: '用于性情、社交和表达方式。',
      yearly: '引动时提示沟通、文书、争议和外部评价。',
      match: '用于关系中误解和沟通风格分析。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.72,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.taiyin.property-wealth.guidance',
    domain: 'combo',
    title: '太阴在田宅或财帛宫',
    entities: ['太阴', '田宅宫', '财帛宫'],
    appliesTo: ['田宅宫', '财帛宫'],
    topics: ['财宅', '积累', '安全感', '不动产'],
    priority: 84,
    guidance: {
      focus: ['财富是否偏向长期积累和稳定资产', '居住环境、家庭安全感和财务安全感的关联', '是否适合稳健理财、不动产或审美生活相关领域'],
      likelyThemes: ['重视安全感和生活品质', '财务和家宅议题常互相牵动', '适合以细腻、耐心和长期规划累积'],
      nuance: ['太阴财宅好不等于必有房产，仍需看亮度、四化和现实条件', '化忌时安全感不足、家宅压力或财务忧虑更明显'],
      avoid: ['不要直接断有房有产', '不要给购房投资建议', '不要忽略情绪安全感'],
    },
    taskFit: {
      natal: '用于财富、安全感和家宅分析。',
      yearly: '引动时看房产、居住、家庭财务和情绪安全感。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.72,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.tianliang.health-parents.guidance',
    domain: 'combo',
    title: '天梁在疾厄或父母宫',
    entities: ['天梁', '疾厄宫', '父母宫'],
    appliesTo: ['疾厄宫', '父母宫'],
    topics: ['照护', '长辈', '健康提醒', '化解'],
    priority: 82,
    guidance: {
      focus: ['长辈、医法、照护和制度资源', '身体问题是否有缓冲和修复条件', '是否以责任感处理家庭或健康议题'],
      likelyThemes: ['容易遇到长辈、专业人士或制度性帮助', '适合重视体检、规律和预防', '也可能承担照顾责任'],
      nuance: ['天梁的化解力不等于没有问题，而是较有缓冲和解决路径', '落疾厄时只宜作保守健康提醒，不可医学诊断'],
      avoid: ['不要写成万能逢凶化吉', '不要做医疗结论', '不要忽略照顾责任带来的压力'],
    },
    taskFit: {
      natal: '用于健康提醒、长辈缘和责任感分析。',
      yearly: '引动时提示体检、长辈、制度和照护事务。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.7,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.taiyang.career.guidance',
    domain: 'combo',
    title: '太阳在官禄宫',
    entities: ['太阳', '官禄宫'],
    appliesTo: ['官禄宫', '事业'],
    topics: ['事业', '公开表达', '服务', '名声'],
    priority: 84,
    guidance: {
      focus: ['事业是否需要公开表达、照顾他人或承担责任', '名声和可见度是否带来机会或压力', '上级、男性贵人和公众评价'],
      likelyThemes: ['适合教育、传播、管理、服务、公职或需要曝光的工作', '事业成就常来自责任感和持续付出'],
      nuance: ['太阳官禄要看亮度和四化，亮度不足或化忌时更易劳而不显', '公开性越强越要管理评价和精力消耗'],
      avoid: ['不要只写事业光明', '不要忽略过度付出和名声压力'],
    },
    taskFit: {
      natal: '用于事业方向和社会角色分析。',
      yearly: '引动时看公开事务、上级关系和责任加重。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.72,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.tianfu.wealth-property.guidance',
    domain: 'combo',
    title: '天府在财帛或田宅宫',
    entities: ['天府', '财帛宫', '田宅宫'],
    appliesTo: ['财帛宫', '田宅宫'],
    topics: ['守成', '资源', '资产', '稳定'],
    priority: 84,
    guidance: {
      focus: ['资源管理和资产沉淀能力', '是否偏好稳健积累和安全边际', '守成是否变成保守或行动慢'],
      likelyThemes: ['财宅主题较重稳定和积累', '适合长期经营、资产配置、管理资源和维持秩序'],
      nuance: ['天府财宅不等于必富，关键在资源是否真实可用和能否主动经营', '煞忌重时可能有守成压力或资源被占用'],
      avoid: ['不要直接断财库丰厚', '不要忽略保守和流动性不足'],
    },
    taskFit: {
      natal: '用于财务稳定性和资产观。',
      yearly: '引动时看资产、房产、储蓄和资源管理。',
      kline: '可降低财务曲线波动。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.72,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.qisha.career.guidance',
    domain: 'combo',
    title: '七杀在官禄宫',
    entities: ['七杀', '官禄宫'],
    appliesTo: ['官禄宫', '事业'],
    topics: ['开创', '竞争', '高压', '执行'],
    priority: 86,
    guidance: {
      focus: ['事业是否处于竞争、高压或开拓环境', '是否需要快速决断和承担风险', '纪律和团队资源是否能驾驭冲劲'],
      likelyThemes: ['适合创业、业务开拓、军警、技术攻坚、项目突围或高压管理', '职业路径可能有明显转折和突破'],
      nuance: ['七杀官禄不是只看危险，重点是压力、决断和开创代价', '若缺乏规则和资源，容易变成硬冲和孤军奋战'],
      avoid: ['不要只写事业凶险', '不要忽略其突破和承担能力'],
    },
    taskFit: {
      natal: '用于事业压力和开创路径。',
      yearly: '引动时看竞争、转型、项目突破和风险控制。',
      kline: '可提高事业维度波动。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.72,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.tianxiang.career.guidance',
    domain: 'combo',
    title: '天相在官禄宫',
    entities: ['天相', '官禄宫'],
    appliesTo: ['官禄宫', '事业'],
    topics: ['辅佐', '行政', '协调', '制度'],
    priority: 82,
    guidance: {
      focus: ['事业是否依赖协调、制度、行政、顾问或支持角色', '是否重视流程、形象和分寸', '是否容易夹在各方期待之间'],
      likelyThemes: ['适合幕僚、行政、法务合规、品牌形象、顾问和组织协调', '能维持局面但不一定喜欢粗暴开创'],
      nuance: ['天相官禄的价值在成全局面和稳定结构，不应被写成弱势', '遇煞忌时需防人情压力和责任夹缝'],
      avoid: ['不要把辅佐等同无成就', '不要忽略制度和形象管理能力'],
    },
    taskFit: {
      natal: '用于职业角色和工作风格。',
      yearly: '引动时看组织调整、流程责任和协调压力。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.7,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.tiantong.spouse-fortune.guidance',
    domain: 'combo',
    title: '天同在夫妻或福德宫',
    entities: ['天同', '夫妻宫', '福德宫'],
    appliesTo: ['夫妻宫', '福德宫'],
    topics: ['舒适', '照顾', '情绪', '安逸'],
    priority: 80,
    guidance: {
      focus: ['关系和生活是否重舒适、照顾和情绪安顿', '是否容易回避冲突或追求安逸', '伴侣关系能否提供稳定日常感'],
      likelyThemes: ['亲密关系需要温和、轻松和生活气', '精神层面重放松和被照顾感'],
      nuance: ['天同的福气需要适度激励，否则容易拖延或安于现状', '遇煞忌时舒适需求可能转成情绪逃避'],
      avoid: ['不要只写有福和睦', '不要忽略进取不足和回避冲突'],
    },
    taskFit: {
      natal: '用于关系舒适度和福德分析。',
      match: '用于合盘里的日常相处和情绪安顿。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.7,
    reviewStatus: 'draft',
  },
  {
    id: 'combo.lianzhen.spouse-career.guidance',
    domain: 'combo',
    title: '廉贞在夫妻或官禄宫',
    entities: ['廉贞', '夫妻宫', '官禄宫'],
    appliesTo: ['夫妻宫', '官禄宫'],
    topics: ['边界', '规则', '感情', '名誉'],
    priority: 82,
    guidance: {
      focus: ['关系或事业中的规则和边界', '是否涉及名誉、审查、人事复杂或吸引力议题', '欲望和责任如何平衡'],
      likelyThemes: ['感情和事业都不宜边界模糊', '适合重视制度、合约、名誉和清晰承诺'],
      nuance: ['廉贞不应只按桃花解释，在官禄也有制度、管理、公关和审美能力', '化忌时才更强调纠葛和名誉压力'],
      avoid: ['不要直接断桃花是非', '不要用道德审判式语言', '不要忽略制度和能力面'],
    },
    taskFit: {
      natal: '用于感情边界和事业规则。',
      match: '用于关系吸引力、承诺和边界分析。',
      yearly: '引动时看名誉、合约、规则和关系纠葛。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'B',
    confidence: 0.7,
    reviewStatus: 'draft',
  },
]
