/**
 * [INPUT]: Depends on knowledge-db schema and project analysis position
 * [OUTPUT]: Provides global interpretation principles for AI guidance
 * [POS]: Highest-level guardrails shared by natal, yearly, match, kline, and share tasks
 * [PROTOCOL]: Update this header when changed, then check AGENTS.md/CLAUDE.md
 */

import type { KnowledgeEntry } from '../schema'

const SOURCE_REFS = [
  'project.analysis-position',
  'book.ziwei-doushu-quanshu',
  'book.wang-tingzhi-basic',
  'author.cross-check',
]

export const PRINCIPLE_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'principle.chart-facts-first',
    domain: 'principle',
    title: '命盘事实优先',
    entities: ['命盘事实', '排盘结果'],
    appliesTo: ['全局'],
    topics: ['判断顺序', 'AI护栏'],
    priority: 100,
    guidance: {
      focus: ['以程序排盘结果为分析骨架', '不得自行更改星曜、宫位、四化或大限流年位置'],
      likelyThemes: ['先确认命盘事实，再组织解释', '缺失信息只可提示不确定，不可补造'],
      nuance: ['知识库只提供分析导向，不替代排盘结果', '模型可以综合取舍，但不能重新排盘'],
      avoid: ['不要自行推算并覆盖 iztro 结果', '不要因为常识性资料与命盘事实冲突而改写命盘'],
    },
    taskFit: {
      natal: '用于保证本命解读围绕当前命盘。',
      yearly: '用于保证流年分析不脱离指定年份的运限数据。',
      match: '用于保证合盘分别保留两张命盘事实。',
      kline: '用于保证趋势评分基于命盘事实，而不是自由编造。',
      share: '用于保证金句来自当前命盘气质。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'S',
    confidence: 0.95,
    reviewStatus: 'reviewed',
  },
  {
    id: 'principle.guidance-not-verdict',
    domain: 'principle',
    title: '知识导向不是机械判词',
    entities: ['知识库', '导向', '综合判断'],
    appliesTo: ['全局'],
    topics: ['输出风格', 'AI护栏'],
    priority: 98,
    guidance: {
      focus: ['把命中知识自然融入分析', '保留模型的综合表达能力', '用知识库纠偏而不是逐条复述'],
      likelyThemes: ['分析应像专业批注，不像规则清单', '相同知识在不同任务中应换角度解释'],
      nuance: ['知识条目的 focus、nuance、avoid 是提醒，不是固定输出模板'],
      avoid: ['不要逐条朗读知识库', '不要把每个命中项写成生硬结论', '不要使用“必然”“一定”这类绝对化措辞'],
    },
    taskFit: {
      natal: '保持完整、自然、综合的命盘叙述。',
      yearly: '把导向转成当年趋势，而不是复制本命断语。',
      match: '把导向转成互动模式和磨合建议。',
      kline: '把导向转成趋势权重，不输出长篇规则解释。',
      share: '把导向转成有洞察的短句。',
    },
    sourceRefs: ['project.analysis-position', 'author.cross-check'],
    sourceLevel: 'S',
    confidence: 0.95,
    reviewStatus: 'reviewed',
  },
  {
    id: 'principle.no-absolute-fate',
    domain: 'principle',
    title: '避免绝对断事',
    entities: ['吉凶', '趋势', '风险'],
    appliesTo: ['全局'],
    topics: ['风险表达', '用户安全'],
    priority: 96,
    guidance: {
      focus: ['表达倾向、课题、风险和建议', '把凶象写成需管理的变量', '把吉象写成可发挥的条件'],
      likelyThemes: ['吉凶并陈', '趋势判断', '具体建议'],
      nuance: ['煞忌、空宫、落陷等都不应直接等同灾祸或失败', '吉星、庙旺、格局也不应直接等同富贵成功'],
      avoid: ['不要断言必破财、必离婚、必有病灾', '不要提供医疗、法律、投资等确定性结论'],
    },
    taskFit: {
      natal: '用于长期命格分析的措辞边界。',
      yearly: '用于年度风险提示，避免恐吓式输出。',
      match: '用于关系分析，避免断定必分或必成。',
      kline: '用于分数解释，避免把低点说成灾难。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'S',
    confidence: 0.92,
    reviewStatus: 'reviewed',
  },
  {
    id: 'principle.sihua-dynamic-weight',
    domain: 'principle',
    title: '四化作为动态引动',
    entities: ['化禄', '化权', '化科', '化忌', '四化'],
    appliesTo: ['本命', '大限', '流年'],
    topics: ['四化', '动态判断'],
    priority: 94,
    guidance: {
      focus: ['四化提示事项被引动后的方向', '结合所化星曜、本宫主题、三方四正和运限层次'],
      likelyThemes: ['化禄看顺势和资源', '化权看主导和压力', '化科看名誉和缓和', '化忌看执着和消耗'],
      nuance: ['四化不应脱离宫位解释', '同一化象在本命、大限、流年的力度和时间尺度不同'],
      avoid: ['不要把化忌直接等同灾', '不要把化禄直接等同发财', '不要脱离星曜本性解释四化'],
    },
    taskFit: {
      natal: '用于说明一生较常被引动的主题。',
      yearly: '用于说明当年得失、压力和应期方向。',
      match: '用于说明双方互动中谁触发谁的主题。',
      kline: '用于调整趋势波动和风险提示。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'A',
    confidence: 0.88,
    reviewStatus: 'reviewed',
  },
  {
    id: 'principle.layered-time-reading',
    domain: 'principle',
    title: '本命、大限、流年分层',
    entities: ['本命', '大限', '流年'],
    appliesTo: ['运限'],
    topics: ['运势', '时间层次'],
    priority: 92,
    guidance: {
      focus: ['本命看底色与长期结构', '大限看十年阶段主题', '流年看具体年份触发'],
      likelyThemes: ['本命为体', '大限为用', '流年为应'],
      nuance: ['年度分析应避免只看流年，不看本命和大限承接', '大限主题强时，流年事件多围绕该阶段课题展开'],
      avoid: ['不要用单一年份覆盖整个命格', '不要把流年小波动说成终身定论'],
    },
    taskFit: {
      yearly: '年度运势的核心判断原则。',
      kline: '人生 K 线应体现大限阶段感和流年波动。',
      natal: '本命解读可轻量提示未来阶段，但不应展开过多年份细节。',
    },
    sourceRefs: SOURCE_REFS,
    sourceLevel: 'A',
    confidence: 0.86,
    reviewStatus: 'reviewed',
  },
  {
    id: 'principle.domain-safety-health-wealth-relationship',
    domain: 'principle',
    title: '健康财务关系领域安全表达',
    entities: ['健康', '财务', '关系', '安全表达'],
    appliesTo: ['全局'],
    topics: ['用户安全', '风险表达', '建议边界'],
    priority: 95,
    guidance: {
      focus: ['健康只做作息、体检、风险管理提醒', '财务只做预算、现金流、合同和风险意识提醒', '关系只做互动模式和沟通建议'],
      likelyThemes: ['高风险领域要避免确定性结论', '建议应可执行但不越界', '用“倾向、提醒、适合关注”替代“必然、一定”'],
      nuance: ['AI 命理分析是辅助理解，不是医疗、投资或法律意见', '越敏感的主题越需要温和和条件化表达'],
      avoid: ['不要诊断疾病或给治疗方案', '不要给买卖投资指令', '不要断定离婚、死亡、灾祸'],
    },
    taskFit: {
      natal: '用于综合解读中的敏感领域边界。',
      yearly: '用于年度风险提醒。',
      match: '用于关系判断边界。',
      kline: '用于低分年份表达边界。',
    },
    sourceRefs: ['project.analysis-position', 'author.cross-check'],
    sourceLevel: 'S',
    confidence: 0.96,
    reviewStatus: 'reviewed',
  },
  {
    id: 'principle.share-quote-specificity',
    domain: 'principle',
    title: '分享金句具体性原则',
    entities: ['分享', '金句', '命格金句'],
    appliesTo: ['分享', '命格金句'],
    topics: ['表达', '分享', '具体洞察'],
    priority: 82,
    guidance: {
      focus: ['金句要从命宫主星、核心四化或格局提炼', '表达具体性格洞察而不是泛鸡汤', '短句应有画面、节奏和可识别的人格特征'],
      likelyThemes: ['一句话点出优势', '一句话点出盲点', '一句话给出自我调适方向'],
      nuance: ['分享内容可以有诗意，但不能脱离命盘事实', '幽默、自嘲、温柔或霸气都应贴合命盘气质'],
      avoid: ['不要写“你很好，要相信自己”这类空话', '不要为了传播性夸大吉凶', '不要泄露敏感出生信息'],
    },
    taskFit: {
      share: '用于分享卡片和命格金句提炼。',
      natal: '用于 AI 解读末尾金句段落。',
    },
    sourceRefs: ['project.analysis-position', 'author.cross-check'],
    sourceLevel: 'S',
    confidence: 0.9,
    reviewStatus: 'reviewed',
  },
]
