import type { BirthInfo } from './astro'
import {
  BAZI_TEN_GOD_LABELS,
  buildBaziFourPillars,
  getBaziTenGod,
  type BaziTenGod,
} from './bazi-four-pillars'

type DirectionalTenGod = Exclude<BaziTenGod, 'dayMaster'>

export type BaziDayBranchRelationKind =
  | 'same'
  | 'sixHarmony'
  | 'sixClash'
  | 'unclassified'

export interface BaziCompatibilityPerson {
  dayMaster: {
    stem: string
    element: string
    polarity: string
  }
  dayPillar: {
    stem: string
    branch: string
    ganZhi: string
  }
}

export interface BaziDirectionalRelationship {
  relationship: DirectionalTenGod
  label: string
  description: string
}

export interface BaziDayBranchRelation {
  kind: BaziDayBranchRelationKind
  label: string
  description: string
}

export interface BaziCompatibilityResult {
  personA: BaziCompatibilityPerson
  personB: BaziCompatibilityPerson
  personAToB: BaziDirectionalRelationship
  personBToA: BaziDirectionalRelationship
  dayBranchRelation: BaziDayBranchRelation
  provisional: boolean
}

const SIX_HARMONY_PAIRS = new Set([
  '丑|子',
  '亥|寅',
  '卯|戌',
  '辰|酉',
  '巳|申',
  '午|未',
])

const SIX_CLASH_PAIRS = new Set([
  '午|子',
  '丑|未',
  '寅|申',
  '卯|酉',
  '戌|辰',
  '亥|巳',
])

const RELATIONSHIP_STRUCTURE: Record<DirectionalTenGod, string> = {
  peer: 'the same element and polarity',
  robWealth: 'the same element with opposite polarity',
  eatingGod: 'an element generated by the source, with matching polarity',
  hurtingOfficer: 'an element generated by the source, with opposite polarity',
  indirectWealth: 'an element controlled by the source, with matching polarity',
  directWealth: 'an element controlled by the source, with opposite polarity',
  sevenKillings: 'an element that controls the source, with matching polarity',
  directOfficer: 'an element that controls the source, with opposite polarity',
  indirectResource: 'an element that generates the source, with matching polarity',
  directResource: 'an element that generates the source, with opposite polarity',
}

function orderedPair(first: string, second: string): string {
  return [first, second].sort().join('|')
}

export function getBaziDayBranchRelation(
  firstBranch: string,
  secondBranch: string,
): BaziDayBranchRelation {
  if (firstBranch === secondBranch) {
    return {
      kind: 'same',
      label: 'Same day branch',
      description: 'Both Day Pillars use the same earthly branch. This marks shared structure, not a compatibility outcome.',
    }
  }

  const pair = orderedPair(firstBranch, secondBranch)
  if (SIX_HARMONY_PAIRS.has(pair)) {
    return {
      kind: 'sixHarmony',
      label: 'Six Harmony · Liu He',
      description: 'The two day branches form one of the six canonical Liu He pairs. It is a named structural contact, not a guarantee of harmony.',
    }
  }
  if (SIX_CLASH_PAIRS.has(pair)) {
    return {
      kind: 'sixClash',
      label: 'Six Clash · Liu Chong',
      description: 'The two day branches form one of the six canonical Liu Chong oppositions. It identifies contrast, not a predicted conflict.',
    }
  }

  return {
    kind: 'unclassified',
    label: 'No same / Liu He / Liu Chong pair',
    description: 'This day-branch pair is not same-branch, Six Harmony, or Six Clash. Other systems are intentionally not inferred here.',
  }
}

function buildDirectionalRelationship(
  sourceStem: string,
  targetStem: string,
): BaziDirectionalRelationship | null {
  const relationship = getBaziTenGod(sourceStem, targetStem)
  if (!relationship) return null

  return {
    relationship,
    label: BAZI_TEN_GOD_LABELS[relationship],
    description: `From this Day Master, the other Day Master is ${RELATIONSHIP_STRUCTURE[relationship]}.`,
  }
}

function buildPerson(info: BirthInfo): BaziCompatibilityPerson | null {
  const resolved = info.resolvedBirthTime
  if (!resolved) return null

  const pillars = buildBaziFourPillars({
    year: resolved.year,
    month: resolved.month,
    day: resolved.day,
    timeIndex: resolved.timeIndex,
  })
  const dayPillar = pillars?.pillars.find((pillar) => pillar.scope === 'day')
  if (!pillars || !dayPillar) return null

  return {
    dayMaster: pillars.dayMaster,
    dayPillar: {
      stem: dayPillar.stem,
      branch: dayPillar.branch,
      ganZhi: dayPillar.ganZhi,
    },
  }
}

export function buildBaziCompatibility(
  personAInfo: BirthInfo,
  personBInfo: BirthInfo,
): BaziCompatibilityResult | null {
  const personA = buildPerson(personAInfo)
  const personB = buildPerson(personBInfo)
  if (!personA || !personB) return null

  const personAToB = buildDirectionalRelationship(
    personA.dayMaster.stem,
    personB.dayMaster.stem,
  )
  const personBToA = buildDirectionalRelationship(
    personB.dayMaster.stem,
    personA.dayMaster.stem,
  )
  if (!personAToB || !personBToA) return null

  return {
    personA,
    personB,
    personAToB,
    personBToA,
    dayBranchRelation: getBaziDayBranchRelation(
      personA.dayPillar.branch,
      personB.dayPillar.branch,
    ),
    provisional: personAInfo.birthTimeReliable === false
      || personBInfo.birthTimeReliable === false,
  }
}
