import type { BirthInfo } from './astro'
import {
  BAZI_TEN_GOD_LABELS,
  buildBaziFourPillars,
  getBaziTenGod,
  type BaziPillarScope,
  type BaziTenGod,
} from './bazi-four-pillars'

type DirectionalTenGod = Exclude<BaziTenGod, 'dayMaster'>

export type BaziDayBranchRelationKind =
  | 'same'
  | 'sixHarmony'
  | 'sixClash'
  | 'unclassified'

export interface BaziCompatibilityPerson {
  dayMaster: {
    stem: string
    element: string
    polarity: string
  }
  dayPillar: {
    stem: string
    branch: string
    ganZhi: string
  }
  pillars: Array<{
    scope: BaziPillarScope
    stem: string
    branch: string
    ganZhi: string
    hiddenStems: string[]
  }>
}

export interface BaziDirectionalRelationship {
  relationship: DirectionalTenGod
  label: string
  description: string
}

export interface BaziDayBranchRelation {
  kind: BaziDayBranchRelationKind
  label: string
  description: string
}

export interface BaziPillarBranchContact {
  personAScope: BaziPillarScope
  personABranch: string
  personBScope: BaziPillarScope
  personBBranch: string
  kind: Exclude<BaziDayBranchRelationKind, 'unclassified'>
  label: string
}

export interface BaziPillarStemRelationship {
  targetScope: BaziPillarScope
  targetStem: string
  relationship: DirectionalTenGod
  label: string
}

export interface BaziPillarHiddenStemRelationship {
  targetScope: BaziPillarScope
  targetBranch: string
  targetStem: string
  hiddenStemIndex: number
  relationship: DirectionalTenGod
  label: string
}

export interface BaziCompatibilityResult {
  personA: BaziCompatibilityPerson
  personB: BaziCompatibilityPerson
  personAToB: BaziDirectionalRelationship
  personBToA: BaziDirectionalRelationship
  dayBranchRelation: BaziDayBranchRelation
  branchContacts: BaziPillarBranchContact[]
  stemRelationships: {
    personAToB: BaziPillarStemRelationship[]
    personBToA: BaziPillarStemRelationship[]
  }
  hiddenStemRelationships: {
    personAToB: BaziPillarHiddenStemRelationship[]
    personBToA: BaziPillarHiddenStemRelationship[]
  }
  provisional: boolean
}

const SIX_HARMONY_PAIRS = new Set([
  '丑|子',
  '亥|寅',
  '卯|戌',
  '辰|酉',
  '巳|申',
  '午|未',
])

const SIX_CLASH_PAIRS = new Set([
  '午|子',
  '丑|未',
  '寅|申',
  '卯|酉',
  '戌|辰',
  '亥|巳',
])

const BRANCH_CONTACT_LABELS: Record<BaziPillarBranchContact['kind'], string> = {
  same: 'Same branch',
  sixHarmony: 'Six Harmony · Liu He',
  sixClash: 'Six Clash · Liu Chong',
}

const RELATIONSHIP_STRUCTURE: Record<DirectionalTenGod, string> = {
  peer: 'the same element and polarity',
  robWealth: 'the same element with opposite polarity',
  eatingGod: 'an element generated by the source, with matching polarity',
  hurtingOfficer: 'an element generated by the source, with opposite polarity',
  indirectWealth: 'an element controlled by the source, with matching polarity',
  directWealth: 'an element controlled by the source, with opposite polarity',
  sevenKillings: 'an element that controls the source, with matching polarity',
  directOfficer: 'an element that controls the source, with opposite polarity',
  indirectResource: 'an element that generates the source, with matching polarity',
  directResource: 'an element that generates the source, with opposite polarity',
}

function orderedPair(first: string, second: string): string {
  return [first, second].sort().join('|')
}

export function getBaziDayBranchRelation(
  firstBranch: string,
  secondBranch: string,
): BaziDayBranchRelation {
  if (firstBranch === secondBranch) {
    return {
      kind: 'same',
      label: 'Same day branch',
      description: 'Both Day Pillars use the same earthly branch. This marks shared structure, not a compatibility outcome.',
    }
  }

  const pair = orderedPair(firstBranch, secondBranch)
  if (SIX_HARMONY_PAIRS.has(pair)) {
    return {
      kind: 'sixHarmony',
      label: 'Six Harmony · Liu He',
      description: 'The two day branches form one of the six canonical Liu He pairs. It is a named structural contact, not a guarantee of harmony.',
    }
  }
  if (SIX_CLASH_PAIRS.has(pair)) {
    return {
      kind: 'sixClash',
      label: 'Six Clash · Liu Chong',
      description: 'The two day branches form one of the six canonical Liu Chong oppositions. It identifies contrast, not a predicted conflict.',
    }
  }

  return {
    kind: 'unclassified',
    label: 'No same / Liu He / Liu Chong pair',
    description: 'This day-branch pair is not same-branch, Six Harmony, or Six Clash. Other systems are intentionally not inferred here.',
  }
}

function buildDirectionalRelationship(
  sourceStem: string,
  targetStem: string,
): BaziDirectionalRelationship | null {
  const relationship = getBaziTenGod(sourceStem, targetStem)
  if (!relationship) return null

  return {
    relationship,
    label: BAZI_TEN_GOD_LABELS[relationship],
    description: `From this Day Master, the other Day Master is ${RELATIONSHIP_STRUCTURE[relationship]}.`,
  }
}

function buildPerson(info: BirthInfo): BaziCompatibilityPerson | null {
  const resolved = info.resolvedBirthTime
  if (!resolved) return null

  const pillars = buildBaziFourPillars({
    year: resolved.year,
    month: resolved.month,
    day: resolved.day,
    timeIndex: resolved.timeIndex,
  })
  const dayPillar = pillars?.pillars.find((pillar) => pillar.scope === 'day')
  if (!pillars || !dayPillar) return null

  return {
    dayMaster: pillars.dayMaster,
    dayPillar: {
      stem: dayPillar.stem,
      branch: dayPillar.branch,
      ganZhi: dayPillar.ganZhi,
    },
    pillars: pillars.pillars.map((pillar) => ({
      scope: pillar.scope,
      stem: pillar.stem,
      branch: pillar.branch,
      ganZhi: pillar.ganZhi,
      hiddenStems: pillar.hiddenStems.map(({ stem }) => stem),
    })),
  }
}

function buildPillarBranchContacts(
  personA: BaziCompatibilityPerson,
  personB: BaziCompatibilityPerson,
): BaziPillarBranchContact[] {
  const contacts: BaziPillarBranchContact[] = []

  for (const personAPillar of personA.pillars) {
    for (const personBPillar of personB.pillars) {
      const relation = getBaziDayBranchRelation(
        personAPillar.branch,
        personBPillar.branch,
      )

      if (relation.kind === 'unclassified') continue

      contacts.push({
        personAScope: personAPillar.scope,
        personABranch: personAPillar.branch,
        personBScope: personBPillar.scope,
        personBBranch: personBPillar.branch,
        kind: relation.kind,
        label: BRANCH_CONTACT_LABELS[relation.kind],
      })
    }
  }

  return contacts
}

function buildPillarStemRelationships(
  sourceDayMaster: string,
  target: BaziCompatibilityPerson,
): BaziPillarStemRelationship[] {
  return target.pillars.flatMap((pillar) => {
    const relationship = getBaziTenGod(sourceDayMaster, pillar.stem)
    if (!relationship) return []

    return [{
      targetScope: pillar.scope,
      targetStem: pillar.stem,
      relationship,
      label: BAZI_TEN_GOD_LABELS[relationship],
    }]
  })
}

function buildPillarHiddenStemRelationships(
  sourceDayMaster: string,
  target: BaziCompatibilityPerson,
): BaziPillarHiddenStemRelationship[] {
  return target.pillars.flatMap((pillar) => (
    pillar.hiddenStems.flatMap((targetStem, hiddenStemIndex) => {
      const relationship = getBaziTenGod(sourceDayMaster, targetStem)
      if (!relationship) return []

      return [{
        targetScope: pillar.scope,
        targetBranch: pillar.branch,
        targetStem,
        hiddenStemIndex,
        relationship,
        label: BAZI_TEN_GOD_LABELS[relationship],
      }]
    })
  ))
}

export function buildBaziCompatibility(
  personAInfo: BirthInfo,
  personBInfo: BirthInfo,
): BaziCompatibilityResult | null {
  const personA = buildPerson(personAInfo)
  const personB = buildPerson(personBInfo)
  if (!personA || !personB) return null

  const personAToB = buildDirectionalRelationship(
    personA.dayMaster.stem,
    personB.dayMaster.stem,
  )
  const personBToA = buildDirectionalRelationship(
    personB.dayMaster.stem,
    personA.dayMaster.stem,
  )
  if (!personAToB || !personBToA) return null

  return {
    personA,
    personB,
    personAToB,
    personBToA,
    dayBranchRelation: getBaziDayBranchRelation(
      personA.dayPillar.branch,
      personB.dayPillar.branch,
    ),
    branchContacts: buildPillarBranchContacts(personA, personB),
    stemRelationships: {
      personAToB: buildPillarStemRelationships(personA.dayMaster.stem, personB),
      personBToA: buildPillarStemRelationships(personB.dayMaster.stem, personA),
    },
    hiddenStemRelationships: {
      personAToB: buildPillarHiddenStemRelationships(
        personA.dayMaster.stem,
        personB,
      ),
      personBToA: buildPillarHiddenStemRelationships(
        personB.dayMaster.stem,
        personA,
      ),
    },
    provisional: personAInfo.birthTimeReliable === false
      || personBInfo.birthTimeReliable === false,
  }
}
